### ISSUE TITLE
Problems getting survey responses

### ISSUE THREAD

**Issue by CindyUsingSurveyMonkey** [bcemmett/SurveyMonkeyApi-v3#1]
UPDATE:  Please ignore.  I am brand new to Surveymonkey API.  Did not have Responses data enabled in my setting.
GetSurveyList and GetSurveyDetails work great.
GetSurveyResponseOverviewList and GetSurveyResponseDetailsList hang.
I see that the V3 library is brand new.  Should I be using the V2 library?
Thanks!
Cindy

**Comment by bcemmett** [comment]
Cool - I think appearing to hang would probably be that the web request was failing and the retry logic was waiting before trying again. Think I'll enhance that so that in future only connectivity issues get retried, and issues which are not likely to be related to the network fail immediately.
