### ISSUE TITLE
How do I retrieve weight ID after PopulateSurveyResponseInformation

### ISSUE THREAD

**Issue by bobhuang1** [bcemmett/SurveyMonkeyApi-v3#13]
I do not see weight ID in any of the classes, how do I retrieve it from the ResponseQuestion structure after PopulateSurveyResponseInformation? Thanks much!

**Comment by bcemmett** [comment]
Survey.Questions.Answers.Choices.Weight is the value you're looking for. If you're working with a ResponseQuestion, you'd need to look up the weight using the ChoiceId from ResponseQuestion.Answers to find a Survey.Questions.Answers.Choices with the same Id.

**Comment by bobhuang1** [comment]
Thank you! Works great!
