### ISSUE TITLE
Get the recipient email for each survey

### ISSUE THREAD

**Issue by saboehnke** [bcemmett/SurveyMonkeyApi-v3#16]
I am trying to access the information for the recipient of each survey. How do I access the recipient information? I don't see a direct way to access a particular recipient even though each Response has a recipientId. Also the recipientId seems to be null for all survey instances for some reason.

**Comment by bcemmett** [comment]
I believe the RecipientId is a value that SurveyMonkey uses for email collectors. Possibly the value you're looking for is the RespondentId? (not my choice of naming!)
