### ISSUE TITLE
400 Error

### ISSUE THREAD

**Issue by StephenWallaceGPHG** [bcemmett/SurveyMonkeyApi-v3#19]
Hi 
Using this code (and a valid APIKey, Token ) 

List<SurveyMonkey.Containers.Survey> Updated;
            using (var api = new SurveyMonkeyApi(APIKey, Token))
            {
              Updated = api.GetSurveyList();
            }

I am getting a 400 error (Bad request). Is there some process required that I'm missing?

Steve Wallace

**Comment by bcemmett** [comment]
Afraid I don't know - that should be everything you need. Do you have the View Surveys scope granted on that api key?

**Comment by StephenWallaceGPHG** [comment]
I do .
all of the view scopes and none of the edit scopes.

**Comment by bcemmett** [comment]
Hm. The version of the library released yesterday (3.0.88) will provide more detailed error information for failed web requests. Could you update to that and let me know the details please?

**Comment by bcemmett** [comment]
Right, got it. SurveyMonkey changed the way authentication works recently (they haven't put anything in their updates section), and the result is that for newly registered apps, an api key isn't needed. For now the best thing to do is to pass in an empty string into the SurveyMonkeyApi constructor:

using (var api = new SurveyMonkeyApi(String.Empty, "yourAccessToken"))
{
//etc
}

Let me know if that works?

**Comment by StephenWallaceGPHG** [comment]
That worked perfectly - thank you
