### ISSUE TITLE
api.GetCollectorResponseDetailsList Issue

### ISSUE THREAD

**Issue by vectortonto** [bcemmett/SurveyMonkeyApi-v3#3]
Below you will see a code block that is for the most part working

static void Test2()
        {
            using (var api = new SurveyMonkeyApi("apiKey", "oAuthToken"))
            {
                List<Survey> surveys = api.GetSurveyList();                     //Works
                List<Collector> collectors = api.GetCollectorList(86233126);    //Works

                Collector collector = api.GetCollectorDetails(93166347);       //Works
                List<Response> responses = api.GetCollectorResponseDetailsList(93166347);  //Not Working

            }
        }

List<Response> responses = api.GetCollectorResponseDetailsList(93166347);  //Not Working
The above line returns a 404 error. Is this a bug? I noticed that you have 2 signatures for this
method. The 2nd one takes RequestSettingsGetResponseListSettings. Do I need that in order
to make this call work? I'm running this thing in a console app. If I need that RequestSettingsGetResponseListSettings where do I get it from?

Thanks
--Pat Brown

**Comment by bcemmett** [comment]
Interesting, thanks for reporting. This does seem to work ok for me, and the tests for that pass. SurveyMonkey's v3 api now has the concept of scopes, granting granular permissions over different actions you can take over the api. Is it possible that your key has been set to have permission to view surveys and collectors, bit not responses?

If you go into the settings for you app from https://developer.surveymonkey.net/apps/, can you check that you have the View Responses and View Response Details scopes granted?

Cheers!
Ben

**Comment by bcemmett** [comment]
(you shouldn't need to explicitly pass in a settings object unless you want to filter the information you retrieve)

**Comment by bcemmett** [comment]
Closing as I assume you found this to be the case - reopen or raise another issue if that isn't.

Cheers,
Ben
