### ISSUE TITLE
Get recipients list for each collector

### ISSUE THREAD

**Issue by AswathySNair** [bcemmett/SurveyMonkeyApi-v3#34]
I am trying to retrieve the list of recipients for each collector. What is the API method for the survey monkey end point /collectors/{id}/recipients to return the  list of recipients in each collector.

The existing API method GetRecipientList requires the parameter collectorId and messageId equivalent of survey monkey API /collectors/{id}/messages/{id}/recipients.

Please suggest.Thank you.

**Comment by AswathySNair** [comment]
@bcemmett We have both weblink and email collectors in the survey.I want to retrieve all the respondents of the surevy.The existing API method GetRecipientList requires the parameter collectorId and messageId which will not work for the weblink collectors.Can you please expose a method for retrieving all the recipients for each collector.

**Comment by bcemmett** [comment]
Funnily enough I was just taking a look at this. I missed this because SurveyMonkey only added that endpoint on October 13th, which is after I did the work for most of the rest of the api: https://developer.surveymonkey.com/api/v3/#october-13th-2016. Should have something released in a few minutes.

**Comment by AswathySNair** [comment]
Thank you

**Comment by bcemmett** [comment]
This is done in #38, and included in the latest release, 3.1.116, which you can get from NuGet. Note that this change means that the old method GetRecipientList() is obsolete, and replaced by GetMessageRecipientList(). The new method GetCollectorRecipientList() maps to the endpoint you need.
