### ISSUE TITLE
Proxy Server authentication

### ISSUE THREAD

**Issue by ebenv** [bcemmett/SurveyMonkeyApi-v3#35]
With our network configuration I require proxy custom authentication.  I experimented now with the API to enable one of the internal constructors to allow me to include an instance of my own webclient (based on the LiveWebClient).
When I call it without the web client I get an error that the remote server is blocking my access (Unable to connect to the remote server).
When I call it with my own webclient including the required proxy authentication and call the GetSurveyList method I get an internal NULL reference error (stacktrace below).

I verified my authentication token and the call with Postmaster and it works fine, but seem to miss something in the code.  Is there a way to push through the proxy into the built-in web client (it seems I get further with that one than my own)?

   _```
at SurveyMonkey.SurveyMonkeyApi.ResetWebClient()
   at SurveyMonkey.SurveyMonkeyApi.MakeApiRequest(String endpoint, Verb verb, RequestData data)
   at SurveyMonkey.SurveyMonkeyApi.PageRequest(String url, RequestData requestData, Type type)
   at SurveyMonkey.SurveyMonkeyApi.Page(IPagingSettings settings, String url, Type type, Int32 maxResultsPerPage)
   at SurveyMonkey.SurveyMonkeyApi.GetSurveyListPager(IPagingSettings settings)
   at DET.BSD.Events.DAL.SurveyManager.UpdateAPICallQuotas() in C:\Development\IPL\plisrepo\DAL\SurveyManager.vb:line 231
```_

**Comment by bcemmett** [comment]
Weird - WebClient should pick up proxy settings from the system automatically. Is that not happening, or does your app need to use custom proxy settings which are different to the settings defined in Internet Explorer's LAN settings?

**Comment by ebenv** [comment]
Yes also not sure why. But the way it has been done we often find we have to authenticate the proxy manually through code.

**Comment by bcemmett** [comment]
Weird. Either way, I don't think there's any harm exposing the Proxy object - that's done in #36 and released in 3.1.116, which you can update to from NuGet. You can now access api.Proxy, which lets you write an IWebProxy object directly into the WebClient. I'll close this issue now, please raise a separate issue for your point about exposing quota information - it would be good to keep that separate. Thanks.

**Comment by ebenv** [comment]
Thank you.
