### ISSUE TITLE
Surveys containing >100 pages of questions omit all data after page 100

### ISSUE THREAD

**Issue by mgandley** [bcemmett/SurveyMonkeyApi-v3#37]
This is less an issue with your code and more an issue with the SM API V3.  If you're extracting a survey with >100 pages of questions, the API will only return the first 100 via surveys/{id}/details.

I don't know of a good workaround that isn't API call heavy.  I guess for all questions past page 100, you could get a list of pages via surveys/{id}/pages, then go through each page via surveys/{id}/pages/{id} to get the questions, then go through each question via surveys/{id}/questions/{id} to get the options.  There's no details endpoint for any of them forcing you to call each endpoint individually.

I sent api-support@surveymonkey.com an email asking for them to fix it, as this cutoff isn't documented anywhere.  I'll update this issue with their response once I hear back.  They may just fix it (hopefully) but if not it may require some modifications to code for paging through survey details.

**Comment by mgandley** [comment]
Also, I'll give a little more background on WHY we have a survey with > 100 pages, for those who are reading this issue and are curious.

We send a satisfaction survey to customer organizations.  Many of the questions are very specific to a particular role at this organization, and we don't know who is going to be answering the survey.  Our first page is a routing page: the user selects their role from a drop-down list of roles.  Their selection on this page is used to conditionally show particular relevant pages to the end user.  We have over 100 different configurations of questions that are relevant to the end users based on role, hence > 100 pages.

In practice, a typical user will only answer ~5 or so pages of questions.

**Comment by bcemmett** [comment]
Huh, haven't encountered that before. Would have thought that even if they don't want to return >100 pages of data in one go, it would be sensible for them to allow you to at least page through the survey's pages, 100 pages at a time. Maybe they consider so many pages on a survey too edge casey to bother with that mechanism. Either way, will be interesting to see what they come back with.

**Comment by mgandley** [comment]
They fixed the issue - here's their response:

_The fix is now live, so you should be able to return all survey pages moving forward._ 

Now I'm getting a gateway time-out (504) on calling the API for a large survey.  Consistent with results in Postman, so it's something on their end.  More to come.

**Comment by mgandley** [comment]
SurveyMonkey has fully resolved this issue.  The survey details endpoint successfully returns a 1.5k question survey made of mostly matrix questions in ~10-15 seconds.
