### ISSUE TITLE
Getting opened, unopened, bounced, complete, partially complete survey stats

### ISSUE THREAD

**Issue by saboehnke** [bcemmett/SurveyMonkeyApi-v3#46]
Is there a way to get the statistics for the number of opened, unopened, bounced, complete, and partially complete surveys in this API? Thanks in advance!

**Comment by bcemmett** [comment]
I'm not aware of surveymonkey providing that information anywhere through their api, but it's best to get in touch with them directly to check. If they do surface that information somewhere, let me know and I'll think about adding it to this library (or even better, you could submit a PR).

**Comment by saboehnke** [comment]
I contacted Survey Monkey and they revealed that the complete/partially complete status is accessible and I have found it in your code under Response.ResponseStatus. As for the other statistics they are not currently available in the API but they have submitted tickets to possibly add them in the future. If this happens I can notify you and possibly submit a PR as well. Thanks!
