### ISSUE TITLE
The remote server returned an error: (403) Forbidden when accessing survey responses

### ISSUE THREAD

**Issue by saboehnke** [bcemmett/SurveyMonkeyApi-v3#9]
I have attempted accessing survey responses using the GetCollectorResponseDetailsList() method and I get this error when making the call: "The remote server returned an error: (403) Forbidden". I am able to get the list of surveys just fine. Any idea what this would be?

**Comment by bcemmett** [comment]
SurveyMonkey's v3 api now has the concept of scopes, granting granular permissions over different actions you can take over the api. It's likely that your key has been set to have permission to view surveys, but not responses?

If you go into the settings for you app from https://developer.surveymonkey.net/apps/, can you check that you have the View Responses and View Response Details scopes granted?

**Comment by saboehnke** [comment]
You were right. I didn't have responses enabled. It says that the scope needs to be re-authenticated when scopes change. Do you know if this happens automatically or do I need to do this somehow?

**Comment by saboehnke** [comment]
Yep that was the issue. Thank you for that!
